### PR TITLE
Update sys.kelvin

### PR DESCRIPTION
**Pull request by jamesacklin**

### CODE REVIEW

**Comment by jalehman** [comment]
This probably needs additional changes cc @belisarius222

**Comment by jamesacklin** [comment]
I'll leave this one to the adults.

**Comment by Fang-** [comment]
It probably does not. Webterm as exists in this repo is just a js bundle. Everything that isn't /mar/docket or its supporting code can and should probably be removed, but that's outside of scope here. In any case, even if we keep including the /sur/hood.hoon, we don't import it for builds anywhere, because nothing gets built aside from the .docket file (and sys.kelvin and other such mandatory desk attributes).

**Review by Fang- — APPROVED** [review]
This seems perfectly fine to me.

**Comment by jalehman** [comment]
@pkova Can you verify that this works and ship the update?

**Comment by belisarius222** [comment]
My ship still has the old version of webterm before this commit:
```
> +vat %webterm
%webterm
  /sys/kelvin:      [%zuse 416] [%zuse 415]
  base hash:        0v3.0chi4.jv46l.iaspp.tkl3b.543du.qv8le.0do0m.7qd6j.tm99l.tmo1e
  %cz hash:         0v3.0chi4.jv46l.iaspp.tkl3b.543du.qv8le.0do0m.7qd6j.tm99l.tmo1e
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~binnec-dozzod-marzod
  source desk:      %webterm
  source aeon:      6
  kids desk:        ~
  pending updates:  ~
::
~rovnys-ricfer:dojo> 
```

**Pull request merged**
